### ISSUE TITLE
♻️ 사용자 프로필 정보 수정 리팩토링

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/10-team-joytas-dao-be#147]
### ♻️ 진행할 작업 설명

```markdown
기존에 사용자 정보 수정시 닉네임만 변경할 수 있었던 부분을 닉네임과 프로필 이미지 모두 변경할 수 있도록 수정
```

### ☘️TODO

- [x] 사용자 정보 수정 도메인 로직 추가
- [x] 엔드포인트 수정 (`/api/v1/users/nickname` -> `/api/v1/users`)
- [x] Request Body 에 프로필 이미지 주소 필드 추가
