### ISSUE TITLE
♻️ 채팅 도메인 리팩토링

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/10-team-joytas-dao-be#161]
### ♻️ 진행할 작업 설명

```markdown
채팅 도메인 리팩토링
```

### ☘️TODO

- [x] ChatService, ChatRoomService 통합
- [ ] 채팅 메시지 저장 구조 변경
- [ ] 유저 정보 저장 로직
- [ ] 전송자 닉네임, 프로필 이미지 주소 변경 이벤트 추가
