### ISSUE TITLE
♻️ 오브제 도메인 리팩토링

### ISSUE THREAD

**Issue by jjikky** [100-hours-a-week/10-team-joytas-dao-be#164]
### ♻️ 진행할 작업 설명

```markdown
오브제 도메인 리팩토링
```

### ☘️TODO

- [x] ♻️ 오브제 생성 리팩토링
- [x] ♻️ 오브제 수정 리팩토링
- [x] ♻️ 오브제 상세조회 리팩토링
- [x] ♻️ 유저 오브제 조회 리팩토링
- [x] ♻️ 오브제 삭제 리팩토링
