### ISSUE TITLE
✨ 프로덕션 배포 자동화 추가

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/10-team-joytas-dao-be#171]
### ✨ 진행할 작업 설명

```markdown
프로덕션 서버를 위한 프로퍼티 설정 및 프로덕션 서버 배포 자동화 스크립트 추가
```

### 🚀 TODO

- [x] 프로덕션 서버 배포 자동화 스크립트 추가
- [x] 프로덕션 서버 도커 이미지 파일 추가
- [x] 프로덕션 애플리케이션 프로퍼티 설정 추가
