### ISSUE TITLE
♻️ 오브제 도메인 리팩토링

### ISSUE THREAD

**Issue by jjikky** [100-hours-a-week/10-team-joytas-dao-be#199]
### ♻️ 진행할 작업 설명

```markdown
코드의 가독성및 유지보수성 개선을 위해 오브제 도메인 리팩토링을 진행
```

### ☘️TODO

- [x] 과도하게 긴 data  메서드 jpql로 변경
- [x] sharer -> isSharer로 변수 네이밍 명확하게 변경
- [x] facadeService 로직 개선
- [x] objetDetailInfoDto 빌더 패턴 제거
- [x] 오브제 상세 조회 불필요한 데이터 삭제
- [x] 오브제 상태 검증
