### ISSUE TITLE
✨ 라운지 삭제 이벤트 구독 발행 로직 추가

### ISSUE THREAD

**Issue by jjikky** [100-hours-a-week/10-team-joytas-dao-be#202]
### ✨ 진행할 작업 설명

```markdown
라운지 삭제 이벤트 구독 발행 로직 추가
```

### 🚀 TODO

- [x] EDA 방식으로 전환하기 위한 작업 및 의사결정 변경으로 롤백
- [x] 라운지 삭제 이벤트 구독 로직 추가
- [x] 시그널링 인증 로직 리팩토링
