### ISSUE TITLE
♻️ 인증 및 회원 도메인 리팩토링

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/10-team-joytas-dao-be#209]
### ♻️ 진행할 작업 설명

```markdown
회원 도메인과 인증 도메인의 책임의 경계성이 모호한 부분 개선 및 인증 도메인에서 토큰을 핸들링하는 로직 리팩토링
```

### ☘️TODO

- [x] 회원탈퇴에 대한 책임을 `auth` 도메인에서 `user` 도메인으로 이전
- [x] 활성화된 사용자를 가져오는 로직을 삭제되지 않은 사용자를 가져오도록 수정
- [x] `access_token` 을 핸들링하는 로직 리팩토링
