### ISSUE TITLE
♻️ 오브제 도메인 리팩토링

### ISSUE THREAD

**Issue by jjikky** [100-hours-a-week/10-team-joytas-dao-be#216]
### ♻️ 진행할 작업 설명

```markdown
오브제 도메인 리팩토링
```

### ☘️TODO

- [x] 오브제 엔티티 수정
- [x] 오브제 생성 수정 삭제 반환 타입 변경
- [x] 오브제 퍼샤드 패턴 제거
- [x] 오브제 상세 조회 api 분리
- [x] 오브제 공유자 조회 api 추가
- [x] 오브제 음성통화 참가자 수 조회 api 추가
- [x] 오브제 통화 라운지 검증 로직 삭제 ( 라운지 도메인으로 이전 )
- [x] 오브제 목록 조회 응답 데이터 추가
- [x] 오브제 조회 관련 응답 owner depth 추가
- [x] 불필요한 코드 제거
- [x] 오브제 생성 삭제 이벤트 발행
