### ISSUE TITLE
♻️ 회원탈퇴 기능 리팩토링

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/10-team-joytas-dao-be#219]
### ♻️ 진행할 작업 설명

```markdown
deprecated 된 인증 도메인의 회원탈퇴 기능 삭제 및 회원탈퇴시 `deleted_at` 시간이 등록되도록 수정
```

### ☘️TODO

- [ ] deprecated 된 인증 도메인의 회원탈퇴 기능 삭제
- [ ] `BaseTimeEntity` 에서 삭제 시간을 업데이트할 수 있는 메서드 추가
- [ ] 회원탈퇴시 삭제 시간이 갱신되도록 수정
