### ISSUE TITLE
♻️ 오브제 생성시 채팅방 생성 로직 이벤트 처리

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/10-team-joytas-dao-be#223]
### ♻️ 진행할 작업 설명

```markdown
 오브제 생성시 채팅방 생성 로직 이벤트 처리
```

### ☘️TODO

- [x] 오브제 생성시 채팅 도메인에 이벤트 리스너 추가
- [x] 오브제 생성시 채팅방 생성 로직 추가
- [x] 채팅방 엔티티에 오브제 컬럼 추가 (오브제에 있던 채팅방 컬럼 제거)
- [x] 채팅방 엔티티에 오브제 컬럼 추가를 위한 sql문 추가
