### ISSUE TITLE
♻️ 오브제 리팩토링

### ISSUE THREAD

**Issue by jjikky** [100-hours-a-week/10-team-joytas-dao-be#238]
### ♻️ 진행할 작업 설명

```markdown
오브제 도메인에 대해 리팩토링을 수행
```

### ☘️TODO

- [x] 오브제 통화 참가자수 조회 메서드명 변경
- [x] 오브제 수정,삭제 dto 중복 제거  
- [x] 오브제 도메인 로직 리팩토링
- [x] 오브제 예외 타입 리팩토링
- [x] 오브제 존재 유무 검증 로직 리팩토링
