### ISSUE TITLE
✅ 라운지 도메인 단위 테스트 코드 추가 및 리팩토링

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/10-team-joytas-dao-be#246]
### ✨ 진행할 작업 설명

```markdown
 라운지 도메인 단위 테스트 코드 추가 및 리팩토링
```

### 🚀 TODO

- [x] Lounge 테스트 코드 추가
- [x] LoungeStatus 테스트 코드 추가
- [x] LoungeSharer 테스트 코드 추가
- [x] LoungeFixtures, LoungeSharerFixtures 추가
- [x] 리팩토링
