### ISSUE TITLE
♻️ 라운지 도메인 리팩토링

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/10-team-joytas-dao-be#256]
### ♻️ 진행할 작업 설명

```markdown
라운지 도메인 리팩토링
```

### ☘️TODO

- [x] 코드 컨벤션 (변수명) 통일
- [x] 라운지 이벤트 네이밍 과겨형으로 수정
- [x] 라운지 초대 이벤트에 라운지 아이디 추가
