### ISSUE TITLE
♻️ 채팅, 라운지 도메인 변수명 컨벤션 통일 및 리팩토링

### ISSUE THREAD

**Issue by junseoparkk** [100-hours-a-week/10-team-joytas-dao-be#258]
### ♻️ 진행할 작업 설명

```markdown
채팅, 라운지 도메인 변수명 컨벤션 통일 및 리팩토링
```

### ☘️TODO

- [X] 라운지에서 양방향 일대다 관계인 엔티티 의존성 제거
- [X] 라운지, 채팅 도메인에서 컬렉션을 사용하는 변수명 변경 
    - ex) lounges -> loungeList
- [X] 라운지 상세 조회시 오브제 정보 리스트 제거 (API 분리)

### 🐋 연관된 이슈

- closed #161 
- closed #256
