### ISSUE TITLE
✨오브제 공유자 상태 추가

### ISSUE THREAD

**Issue by jjikky** [100-hours-a-week/10-team-joytas-dao-be#265]
### ✨ 진행할 작업 설명

```markdown
라운지 탈퇴 / 재가입시 오브제 공유자 상태로 제어가 필요하여 추가
```

### 🚀 TODO

- [x] 오브제 공유자 상태 추가 마이그레이션 파일 추가
- [x] 라운지 탈퇴 이벤트 구독 로직 추가
- [x] 오브제 공유자 상태 기반 로직 적용
